/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Api from "../../../index";
export declare namespace Websites {
    interface Options {
        environment?: core.Supplier<environments.ApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Websites {
    protected readonly _options: Websites.Options;
    constructor(_options: Websites.Options);
    /**
     * ---
     * title: List websites
     * group: [ENDPOINTS]
     * ---
     *
     * List of all websites
     *
     * @param {Websites.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.BadRequestError}
     * @throws {@link Api.InternalServerError}
     *
     * @example
     *     await client.websites.list()
     */
    list(requestOptions?: Websites.RequestOptions): Promise<Api.Website[]>;
    /**
     * ---
     * title: Create website
     * group: [ENDPOINTS]
     * ---
     *
     * Create a website
     *
     * @param {Api.WebsiteCreate} request
     * @param {Websites.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.BadRequestError}
     * @throws {@link Api.InternalServerError}
     *
     * @example
     *     await client.websites.create({
     *         host: "host"
     *     })
     */
    create(request: Api.WebsiteCreate, requestOptions?: Websites.RequestOptions): Promise<Api.Website>;
    protected _getCustomAuthorizationHeaders(): Promise<{
        Authorization: string;
    }>;
}
