/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
import { AlertEvent } from "./AlertEvent";
import { AlertProviderEnum } from "./AlertProviderEnum";
export declare const Alert: core.serialization.ObjectSchema<serializers.Alert.Raw, Api.Alert>;
export declare namespace Alert {
    interface Raw {
        alert_id?: string | null;
        name?: string | null;
        events?: AlertEvent.Raw[] | null;
        provider?: AlertProviderEnum.Raw | null;
        slack_channel_id?: string | null;
        webhook_id?: string | null;
        enabled?: boolean | null;
        creation_date?: string | null;
    }
}
