/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const ErrorResponseError: core.serialization.ObjectSchema<serializers.ErrorResponseError.Raw, Api.ErrorResponseError>;
export declare namespace ErrorResponseError {
    interface Raw {
        type?: string | null;
        code?: string | null;
        param?: string | null;
        message?: string | null;
        http_status_code?: number | null;
        request_id?: string | null;
    }
}
