/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
import { Pagination } from "./Pagination";
import { Session } from "./Session";
export declare const GetListSessionsResponse: core.serialization.ObjectSchema<serializers.GetListSessionsResponse.Raw, Api.GetListSessionsResponse>;
export declare namespace GetListSessionsResponse {
    interface Raw {
        total?: number | null;
        page?: Pagination.Raw | null;
        sessions?: Session.Raw[] | null;
    }
}
