/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const OauthScope: core.serialization.Schema<serializers.OauthScope.Raw, Api.OauthScope>;
export declare namespace OauthScope {
    type Raw = "users.sessions:read" | "webhooks:read" | "webhooks:write" | "alerts:read" | "alerts:write" | "websites:read" | "websites:write" | "payment_intents:write" | "payment_intents.confirm";
}
