/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const SessionResolutionData: core.serialization.ObjectSchema<serializers.SessionResolutionData.Raw, Api.SessionResolutionData>;
export declare namespace SessionResolutionData {
    interface Raw {
        height?: number | null;
        width?: number | null;
        resolution?: string | null;
    }
}
