/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const SessionBrowserData: core.serialization.ObjectSchema<serializers.SessionBrowserData.Raw, Api.SessionBrowserData>;
export declare namespace SessionBrowserData {
    interface Raw {
        description?: string | null;
        name?: string | null;
        version?: string | null;
    }
}
