/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const SessionVisitorDataGeolocation: core.serialization.ObjectSchema<serializers.SessionVisitorDataGeolocation.Raw, Api.SessionVisitorDataGeolocation>;
export declare namespace SessionVisitorDataGeolocation {
    interface Raw {
        country_code?: string | null;
        city?: string | null;
        region?: string | null;
    }
}
