/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
import { SessionVisitorData } from "./SessionVisitorData";
import { SessionResolutionData } from "./SessionResolutionData";
import { SessionOsData } from "./SessionOsData";
import { SessionBrowserData } from "./SessionBrowserData";
import { SessionUtmData } from "./SessionUtmData";
import { SessionPageViewsStatisticsData } from "./SessionPageViewsStatisticsData";
import { SessionEventsStatisticsData } from "./SessionEventsStatisticsData";
export declare const Session: core.serialization.ObjectSchema<serializers.Session.Raw, Api.Session>;
export declare namespace Session {
    interface Raw {
        id?: string | null;
        website_id?: string | null;
        session_url?: string | null;
        creation_timestamp?: number | null;
        duration?: number | null;
        end_timestamp?: number | null;
        active_time?: number | null;
        end_url?: string | null;
        expiration_timestamp?: number | null;
        last_event_timestamp?: number | null;
        product?: string | null;
        device?: string | null;
        tags?: string[] | null;
        last_seen_page_view_id?: string | null;
        seen?: boolean | null;
        referrer?: string | null;
        start_url?: string | null;
        visitor_first_session?: boolean | null;
        engagment_score?: number | null;
        visitor?: SessionVisitorData.Raw | null;
        resolution?: SessionResolutionData.Raw | null;
        os?: SessionOsData.Raw | null;
        browser?: SessionBrowserData.Raw | null;
        utm?: SessionUtmData.Raw | null;
        page_views_statistics?: SessionPageViewsStatisticsData.Raw | null;
        events_statistics?: SessionEventsStatisticsData.Raw | null;
    }
}
