/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const SessionOsData: core.serialization.ObjectSchema<serializers.SessionOsData.Raw, Api.SessionOsData>;
export declare namespace SessionOsData {
    interface Raw {
        name?: string | null;
        version?: string | null;
    }
}
