/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const SessionPageViewLocationData: core.serialization.ObjectSchema<serializers.SessionPageViewLocationData.Raw, Api.SessionPageViewLocationData>;
export declare namespace SessionPageViewLocationData {
    interface Raw {
        base?: string | null;
        href?: string | null;
        origin?: string | null;
        referrer?: string | null;
    }
}
