/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const Webhook: core.serialization.ObjectSchema<serializers.Webhook.Raw, Api.Webhook>;
export declare namespace Webhook {
    interface Raw {
        webhook_id?: string | null;
        url?: string | null;
        website?: string | null;
        website_id?: string | null;
        version?: string | null;
        enabled?: boolean | null;
        created_date?: number | null;
        created_by?: string | null;
    }
}
