/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const Website: core.serialization.ObjectSchema<serializers.Website.Raw, Api.Website>;
export declare namespace Website {
    interface Raw {
        website_id?: string | null;
        host?: string | null;
    }
}
