/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         url: "url",
 *         websiteId: "website_id",
 *         version: "version"
 *     }
 */
export interface WebhookCreate {
    /** URL for the webhook */
    url: string;
    /** Website ID */
    websiteId: string;
    /** API version (e.g., v1.0) */
    version: string;
}
