/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface GetSessionsRequest {
    /**
     * The number of page to start with (default 0, max 10000).
     */
    page?: number;
    /**
     * The number of page's size (default 25, max 100).
     */
    size?: number;
    /**
     * The email address that you have associated with a session via [identify](/docs/api/browser/methods#identify).
     */
    email?: string;
    /**
     * The visitor ID.
     */
    visitorId?: string;
    /**
     * IANA timezone. Default Europe/London if RelativeDateString is applied.
     */
    tz?: string;
    /**
     * [ISO 8601](https://wikipedia.org/wiki/ISO_8601) string or [RelativeDateString](/docs/api/rest/RelativeDateString).
     */
    dateFrom?: string;
    /**
     * [ISO 8601](https://wikipedia.org/wiki/ISO_8601) string or [RelativeDateString](/docs/api/rest/RelativeDateString).
     */
    dateTo?: string;
}
