/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Api from "../../../../../api/index";
import * as core from "../../../../../core";
import { AlertEvent } from "../../../../types/AlertEvent";
import { AlertProviderEnum } from "../../../../types/AlertProviderEnum";
export declare const AlertUpdate: core.serialization.Schema<serializers.AlertUpdate.Raw, Api.AlertUpdate>;
export declare namespace AlertUpdate {
    interface Raw {
        name?: string | null;
        events?: AlertEvent.Raw[] | null;
        provider?: AlertProviderEnum.Raw | null;
        slack_channel_id?: string | null;
        webhook_id?: string | null;
    }
}
