/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Api from "../../../../../api/index";
import * as core from "../../../../../core";
import { AlertEvent } from "../../../../types/AlertEvent";
import { AlertProviderEnum } from "../../../../types/AlertProviderEnum";
export declare const AlertCreate: core.serialization.Schema<serializers.AlertCreate.Raw, Api.AlertCreate>;
export declare namespace AlertCreate {
    interface Raw {
        name: string;
        events: AlertEvent.Raw[];
        provider: AlertProviderEnum.Raw;
        slack_channel_id?: string | null;
        webhook_id?: string | null;
    }
}
