/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Api from "../../../../index";
/**
 * @example
 *     {
 *         name: "name",
 *         events: [{}],
 *         provider: "slack"
 *     }
 */
export interface AlertCreate {
    name: string;
    events: Api.AlertEvent[];
    provider: Api.AlertProviderEnum;
    slackChannelId?: string;
    webhookId?: string;
}
