/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Api from "../../../../index";
/**
 * @example
 *     {}
 */
export interface AlertUpdate {
    name?: string;
    events?: Api.AlertEvent[];
    provider?: Api.AlertProviderEnum;
    slackChannelId?: string;
    webhookId?: string;
}
