openapi: 3.1.0

info:
  title: LiveSession API
  version: v1

servers:
  - url: https://api.livesession.io/v1
    description: Production server (uses live data)

paths:
  # BEGIN Sessions
  /sessions:
    get:
      security:
        - livesession_oauth: [ users.sessions:read ]
        - api_token: [ users.sessions:read ]
      summary: Get Sessions
      tags:
        - Sessions
  # BEGIN Alerts
  /alerts:
    get:
      security:
        - livesession_oauth: [ alerts:read ]
      summary: Get all alerts
      tags:
        - Alerts
    post:
      security:
        - livesession_oauth: [ alerts:write ]
      summary: Create an alert
      tags:
        - Alerts
  /alerts/{id}:
    put:
      security:
        - livesession_oauth: [ alerts:write ]
      summary: Update an alert by ID
      tags:
        - Alerts
    delete:
      security:
        - livesession_oauth: [ alerts:write ]
      summary: Delete an alert by ID
      tags:
        - Alerts
  # END Alerts

  # BEGIN Webhooks
  /webhooks:
    get:
      security:
        - livesession_oauth: [ webhooks:read ]
      summary: Get a list of webhooks
      tags:
        - Webhooks
    post:
      security:
        - livesession_oauth: [ webhooks:write ]
      summary: Create a webhook
      tags:
        - Webhooks
  /webhooks/{id}:
    put:
      security:
        - livesession_oauth: [ webhooks:write ]
      summary: Update a webhook
      tags:
        - Webhooks
    delete:
      security:
        - livesession_oauth: [ webhooks:write ]
      summary: Delete a webhook
      tags:
        - Webhooks
  # END Webhooks

  # BEGIN Websites
  /websites:
    get:
      security:
        - livesession_oauth: [ websites:read ]
      summary: Get a list of websites
      tags:
        - Websites
    post:
      security:
        - livesession_oauth: [ websites:write ]
      summary: Create a website
      tags:
        - Websites
  # END Websites

components:
  securitySchemes:
    api_token:
      type: apiKey
      name: Authorization
      description: "[API Tokens](https://developers.livesession.io/rest-api/introduction/#creating-a-personal-access-token)"
      in: header

    livesession_oauth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://apis.livesession.io/accounts/v1/oauth2/authorize # TODO: more friendly url
          tokenUrl: https://apis.livesession.io/accounts/v1/oauth2/access_token # TODO: more friendly url
          refreshUrl: https://apis.livesession.io/accounts/v1/oauth2/access_token # TODO: more friendly url
          scopes:
            users.sessions:read: read user sessions

            webhooks:read: read webhooks
            webhooks:write: write webhooks

            alerts:read: read alerts
            alerts:write: write alerts

            websites:read: read websites
            websites:write: write websites

            payment_intents:write: write payment intents
            payment_intents.confirm: confirm payment intents
