/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface GetSessionsRequest {
    /**
     * The number of page to start with (default 0, max 10000).
     */
    page?: number;
    /**
     * The number of page's size (default 25, max 100).
     */
    size?: number;
    /**
     * The email address that you have associated with a session via [identify](https://developers.livesession.io/javascript-api/methods/#identify).
     */
    email?: string;
    /**
     * The visitor ID.
     */
    visitorId?: string;
    /**
     * IANA timezone. Default Europe/London if RelativeDateString is applied.
     */
    tz?: string;
    /**
     * ISO 8601 string or RelativeDateString. For RelativeDateString see table below for possible values.
     */
    dateFrom?: string;
    /**
     * ISO 8601 string or [RelativeDateString](#/components/schemas/RelativeDateString). For RelativeDateString see table below for possible values.
     */
    dateTo?: string;
}
