"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiClient = void 0;
const Client_1 = require("./api/resources/sessions/client/Client");
const Client_2 = require("./api/resources/alerts/client/Client");
const Client_3 = require("./api/resources/webhooks/client/Client");
const Client_4 = require("./api/resources/websites/client/Client");
class ApiClient {
    constructor(_options) {
        this._options = _options;
    }
    get sessions() {
        var _a;
        return ((_a = this._sessions) !== null && _a !== void 0 ? _a : (this._sessions = new Client_1.Sessions(this._options)));
    }
    get alerts() {
        var _a;
        return ((_a = this._alerts) !== null && _a !== void 0 ? _a : (this._alerts = new Client_2.Alerts(this._options)));
    }
    get webhooks() {
        var _a;
        return ((_a = this._webhooks) !== null && _a !== void 0 ? _a : (this._webhooks = new Client_3.Webhooks(this._options)));
    }
    get websites() {
        var _a;
        return ((_a = this._websites) !== null && _a !== void 0 ? _a : (this._websites = new Client_4.Websites(this._options)));
    }
}
exports.ApiClient = ApiClient;
