/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         host: "host"
 *     }
 */
export interface WebsiteCreate {
    /** Domain name or hostname of the website to track */
    host: string;
    /** Optional description of the website for organization purposes */
    description?: string;
}
