/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Api from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const WebsiteCreate: core.serialization.Schema<serializers.WebsiteCreate.Raw, Api.WebsiteCreate>;
export declare namespace WebsiteCreate {
    interface Raw {
        host: string;
        description?: string | null;
    }
}
