/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Api from "../../../../api/index";
import * as core from "../../../../core";
import { Alert } from "../../../types/Alert";
export declare const Response: core.serialization.Schema<serializers.alerts.list.Response.Raw, Api.Alert[]>;
export declare namespace Response {
    type Raw = Alert.Raw[];
}
