/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type AlertProviderEnum = "slack" | "webhooks";
export declare const AlertProviderEnum: {
    readonly Slack: "slack";
    readonly Webhooks: "webhooks";
};
