/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Api from "../index";
export interface Alert {
    alertId?: string;
    name?: string;
    events?: Api.AlertEvent[];
    provider?: Api.AlertProviderEnum;
    slackChannelId?: string;
    webhookId?: string;
    enabled?: boolean;
    creationDate?: string;
}
