/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface ErrorResponseError {
    type?: string;
    code?: string;
    param?: string;
    message?: string;
    httpStatusCode?: number;
    requestId?: string;
}
