/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Api from "../index";
export interface GetListSessionsResponse {
    total?: number;
    page?: Api.Pagination;
    sessions?: Api.Session[];
}
