"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OauthScope = void 0;
exports.OauthScope = {
    UsersSessionsRead: "users.sessions:read",
    WebhooksRead: "webhooks:read",
    WebhooksWrite: "webhooks:write",
    AlertsRead: "alerts:read",
    AlertsWrite: "alerts:write",
    WebsitesRead: "websites:read",
    WebsitesWrite: "websites:write",
    PaymentIntentsWrite: "payment_intents:write",
    PaymentIntentsConfirm: "payment_intents.confirm",
};
