/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * * `TODAY` - Today since midnight
 * * `YESTERDAY` - Yesterday since midnight
 * * `BEGINNING_OF_WEEK` - Nearest monday since midnight
 * * `BEGINNING_OF_MONTH` - 1st of the month since midnight
 * * `BEGINNING_OF_PREV_MONTH` - Previous 1st of the month since midnight
 * * `TODAY-7DAYS` - Exact 7 days ago since midnight
 * * `TODAY-30DAYS` - Exact 30 days ago since midnight
 */
export type RelativeDateString = "TODAY" | "YESTERDAY" | "BEGINNING_OF_WEEK" | "BEGINNING_OF_MONTH" | "BEGINNING_OF_PREV_MONTH" | "TODAY-7DAYS" | "TODAY-30DAYS";
export declare const RelativeDateString: {
    readonly Today: "TODAY";
    readonly Yesterday: "YESTERDAY";
    readonly BeginningOfWeek: "BEGINNING_OF_WEEK";
    readonly BeginningOfMonth: "BEGINNING_OF_MONTH";
    readonly BeginningOfPrevMonth: "BEGINNING_OF_PREV_MONTH";
    readonly TodayPrevDays: "TODAY-7DAYS";
    readonly TodayPrev30Days: "TODAY-30DAYS";
};
