"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RelativeDateString = void 0;
exports.RelativeDateString = {
    Today: "TODAY",
    Yesterday: "YESTERDAY",
    BeginningOfWeek: "BEGINNING_OF_WEEK",
    BeginningOfMonth: "BEGINNING_OF_MONTH",
    BeginningOfPrevMonth: "BEGINNING_OF_PREV_MONTH",
    TodayPrevDays: "TODAY-7DAYS",
    TodayPrev30Days: "TODAY-30DAYS",
};
