/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Api from "../index";
export interface Session {
    id?: string;
    websiteId?: string;
    sessionUrl?: string;
    creationTimestamp?: number;
    duration?: number;
    endTimestamp?: number;
    activeTime?: number;
    endUrl?: string;
    expirationTimestamp?: number;
    lastEventTimestamp?: number;
    product?: string;
    device?: string;
    tags?: string[];
    lastSeenPageViewId?: string;
    seen?: boolean;
    referrer?: string;
    startUrl?: string;
    visitorFirstSession?: boolean;
    engagmentScore?: number;
    visitor?: Api.SessionVisitorData;
    resolution?: Api.SessionResolutionData;
    os?: Api.SessionOsData;
    browser?: Api.SessionBrowserData;
    utm?: Api.SessionUtmData;
    pageViewsStatistics?: Api.SessionPageViewsStatisticsData;
    eventsStatistics?: Api.SessionEventsStatisticsData;
}
