/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SessionPageViewLocationData {
    base?: string;
    href?: string;
    origin?: string;
    referrer?: string;
}
