/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SessionEventsStatisticsData {
    clicks?: number;
    errorClicks?: number;
    rageClicks?: number;
    errorLogs?: number;
    netErrors?: number;
}
