/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Api from "../index";
export interface SessionVisitorData {
    id?: string;
    ip?: string;
    geolocation?: Api.SessionVisitorDataGeolocation;
    name?: string;
    email?: string;
    emailHash?: string;
    params?: Api.SessionVisitorDataParams[];
    lastSessionTimestamp?: number;
    firstSessionTimestamp?: number;
}
