/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors/index";
import * as Api from "../index";
export declare class InternalServerError extends errors.ApiError {
    constructor(body: Api.ErrorResponse);
}
