/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface AlertDeleted {
    /** ID of the deleted alert */
    alertId?: string;
    /** Confirmation that the alert was deleted */
    deleted?: boolean;
}
