/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Api from "../index";
export interface Alert {
    /** Unique identifier for the alert */
    alertId?: string;
    /** Name of the alert */
    name?: string;
    /** List of events that trigger the alert */
    events?: Api.AlertEvent[];
    /** Notification provider for the alert */
    provider?: Api.AlertProviderEnum;
    /** Slack channel ID for notifications */
    slackChannelId?: string;
    /** Webhook ID for notifications */
    webhookId?: string;
    /** Whether the alert is currently active */
    enabled?: boolean;
    /** [ISO 8601](https://wikipedia.org/wiki/ISO_8601) timestamp when the alert was created */
    creationDate?: string;
}
