/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface AlertEvent {
    /** Kind of event, more info [here](/docs/api/rest/EventKind) */
    kind?: number;
    /** Value or threshold that triggers the alert */
    value?: string;
}
