/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface ErrorResponseError {
    /** Type of error (e.g., validation_error, authentication_error) */
    type?: string;
    /** Machine-readable error code */
    code?: string;
    /** Name of the parameter that caused the error */
    param?: string;
    /** Human-readable error message */
    message?: string;
    /** HTTP status code associated with the error */
    httpStatusCode?: number;
    /** Unique identifier for the request that caused the error */
    requestId?: string;
}
