/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Api from "../index";
export interface GetListSessionsResponse {
    /** Total number of sessions matching the query */
    total?: number;
    page?: Api.Pagination;
    /** List of session objects */
    sessions?: Api.Session[];
}
