/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type OauthScope = 
/**
 * read user sessions */
"users.sessions:read"
/**
 * read webhooks */
 | "webhooks:read"
/**
 * write webhooks */
 | "webhooks:write"
/**
 * read alerts */
 | "alerts:read"
/**
 * write alerts */
 | "alerts:write"
/**
 * read websites */
 | "websites:read"
/**
 * write websites */
 | "websites:write"
/**
 * write payment intents */
 | "payment_intents:write"
/**
 * confirm payment intents */
 | "payment_intents.confirm";
export declare const OauthScope: {
    readonly UsersSessionsRead: "users.sessions:read";
    readonly WebhooksRead: "webhooks:read";
    readonly WebhooksWrite: "webhooks:write";
    readonly AlertsRead: "alerts:read";
    readonly AlertsWrite: "alerts:write";
    readonly WebsitesRead: "websites:read";
    readonly WebsitesWrite: "websites:write";
    readonly PaymentIntentsWrite: "payment_intents:write";
    readonly PaymentIntentsConfirm: "payment_intents.confirm";
};
