/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface Pagination {
    /** Current page number */
    num?: number;
    /** Number of items per page */
    size?: number;
}
