/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SessionEventsStatisticsData {
    /** Total number of clicks during the session */
    clicks?: number;
    /** Number of clicks on error elements */
    errorClicks?: number;
    /** Number of rapid clicks indicating user frustration */
    rageClicks?: number;
    /** Number of JavaScript errors logged */
    errorLogs?: number;
    /** Number of network errors encountered */
    netErrors?: number;
}
