/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SessionUtmData {
    /** UTM source parameter (e.g., google, facebook) */
    source?: string;
    /** UTM medium parameter (e.g., cpc, social) */
    medium?: string;
    /** UTM campaign parameter */
    campaign?: string;
    /** UTM term parameter (search keywords) */
    term?: string;
    /** UTM content parameter */
    content?: string;
}
