/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Api from "../index";
export interface Session {
    /** Unique identifier for the session */
    id?: string;
    /** ID of the website where the session was recorded */
    websiteId?: string;
    /** URL to view the session in LiveSession dashboard */
    sessionUrl?: string;
    /** Unix timestamp when the session was created */
    creationTimestamp?: number;
    /** Total duration of the session in seconds */
    duration?: number;
    /** Unix timestamp when the session ended */
    endTimestamp?: number;
    /** Total time the user was actively interacting with the page in seconds */
    activeTime?: number;
    /** The last URL visited during the session */
    endUrl?: string;
    /** Unix timestamp when the session recording will expire */
    expirationTimestamp?: number;
    /** Unix timestamp of the last event recorded in the session */
    lastEventTimestamp?: number;
    /** Product identifier associated with the session */
    product?: string;
    /** Device type (e.g., desktop, mobile, tablet) */
    device?: string;
    /** Custom tags associated with the session */
    tags?: string[];
    /** ID of the last page view in the session */
    lastSeenPageViewId?: string;
    /** Whether the session has been viewed in the dashboard */
    seen?: boolean;
    /** URL where the user came from before starting the session */
    referrer?: string;
    /** First URL visited during the session */
    startUrl?: string;
    /** Whether this is the visitor's first session */
    visitorFirstSession?: boolean;
    /** Calculated engagement score for the session (0-100) */
    engagmentScore?: number;
    visitor?: Api.SessionVisitorData;
    resolution?: Api.SessionResolutionData;
    os?: Api.SessionOsData;
    browser?: Api.SessionBrowserData;
    utm?: Api.SessionUtmData;
    pageViewsStatistics?: Api.SessionPageViewsStatisticsData;
    eventsStatistics?: Api.SessionEventsStatisticsData;
}
