/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SessionBrowserData {
    /** Full browser description string */
    description?: string;
    /** Browser name (e.g., Chrome, Firefox, Safari) */
    name?: string;
    /** Browser version */
    version?: string;
}
