/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SessionResolutionData {
    /** Screen height in pixels */
    height?: number;
    /** Screen width in pixels */
    width?: number;
    /** Screen resolution (e.g., "1920x1080") */
    resolution?: string;
}
