/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SessionOsData {
    /** Operating system name (e.g., Windows, macOS, iOS) */
    name?: string;
    /** Operating system version */
    version?: string;
}
