/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SessionVisitorDataGeolocation {
    /** Two-letter country code (ISO 3166-1 alpha-2) */
    countryCode?: string;
    /** City name */
    city?: string;
    /** Region or state name */
    region?: string;
}
