/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SessionPageViewLocationData {
    /** Base URL of the page */
    base?: string;
    /** Full URL of the page */
    href?: string;
    /** Origin of the page (protocol + hostname) */
    origin?: string;
    /** URL of the previous page */
    referrer?: string;
}
