/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SessionPageViewViewPortData {
    /** Viewport height in pixels */
    height?: number;
    /** Viewport width in pixels */
    width?: number;
}
