/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface SessionVisitorDataParams {
    /** Parameter name */
    name?: string;
    /** Parameter value */
    value?: string;
}
