/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Api from "../index";
export interface SessionVisitorData {
    /** Unique identifier for the visitor */
    id?: string;
    /** IP address of the visitor */
    ip?: string;
    geolocation?: Api.SessionVisitorDataGeolocation;
    /** Name of the visitor if identified */
    name?: string;
    /** Email address of the visitor if identified */
    email?: string;
    /** Hashed version of the visitor's email for privacy */
    emailHash?: string;
    /** Custom parameters associated with the visitor */
    params?: Api.SessionVisitorDataParams[];
    /** Unix timestamp of the visitor's last session */
    lastSessionTimestamp?: number;
    /** Unix timestamp of the visitor's first session */
    firstSessionTimestamp?: number;
}
