/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface Webhook {
    /** Webhook ID */
    webhookId?: string;
    /** URL for the webhook */
    url?: string;
    /** Website name */
    website?: string;
    /** Website ID */
    websiteId?: string;
    /** API version */
    version?: string;
    /** Webhook enabled status */
    enabled?: boolean;
    /** Unix timestamp for creation date */
    createdDate?: number;
    /** Creator of the webhook */
    createdBy?: string;
}
