/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface WebhookDeleted {
    /** Webhook ID */
    webhookId?: string;
    /** Indicates if the webhook was deleted */
    deleted?: boolean;
}
