/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface Website {
    /** Unique identifier for the website */
    websiteId?: string;
    /** Domain name or hostname of the website (e.g., example.com) */
    host?: string;
}
