/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const ApiEnvironment: {
    readonly Default: "https://api.livesession.io/v1";
};
export type ApiEnvironment = typeof ApiEnvironment.Default;
