"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiEnvironment = void 0;
exports.ApiEnvironment = {
    Default: "https://api.livesession.io/v1",
};
