/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface AlertsDeleteResponse {
    /** ID of the alert that was deleted */
    alertId?: string;
    /** Indicates whether the alert was successfully deleted */
    deleted?: boolean;
}
