/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Api from "../../../../index";
/**
 * @example
 *     {}
 */
export interface AlertUpdate {
    /** New name for the alert */
    name?: string;
    /** Updated list of events that will trigger the alert */
    events?: Api.AlertEvent[];
    /** Updated notification provider for the alert */
    provider?: Api.AlertProviderEnum;
    /** Updated Slack channel ID for notifications */
    slackChannelId?: string;
    /** Updated webhook ID for notifications */
    webhookId?: string;
}
