/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Api from "../../../../index";
/**
 * @example
 *     {
 *         name: "name",
 *         events: [{}],
 *         provider: "slack"
 *     }
 */
export interface AlertCreate {
    /** Name of the alert for easy identification */
    name: string;
    /** List of events that will trigger the alert */
    events: Api.AlertEvent[];
    /** Notification provider for the alert, `slack` or `webhooks` */
    provider: Api.AlertProviderEnum;
    /** Slack channel ID where notifications will be sent (required if provider is `slack`) */
    slackChannelId?: string;
    /** Webhook ID where notifications will be sent (required if provider is `webhooks`) */
    webhookId?: string;
}
