/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         url: "url",
 *         websiteId: "website_id",
 *         webhookUpdateVersion: "version"
 *     }
 */
export interface WebhookUpdate {
    /**
     * API version
     */
    version: "v1.0";
    /** URL for the webhook */
    url: string;
    /** Website ID */
    websiteId: string;
    /** API version (e.g., v1.0) */
    webhookUpdateVersion: string;
}
