/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Api from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const WebhookUpdate: core.serialization.Schema<serializers.WebhookUpdate.Raw, Omit<Api.WebhookUpdate, "version">>;
export declare namespace WebhookUpdate {
    interface Raw {
        url: string;
        website_id: string;
        version: string;
    }
}
