/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../../index";
import * as Api from "../../../../../api/index";
import * as core from "../../../../../core";
export declare const WebhookCreate: core.serialization.Schema<serializers.WebhookCreate.Raw, Api.WebhookCreate>;
export declare namespace WebhookCreate {
    interface Raw {
        url: string;
        website_id: string;
        version: string;
    }
}
