/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Api from "../../../../api/index";
import * as core from "../../../../core";
import { Webhook } from "../../../types/Webhook";
export declare const Response: core.serialization.Schema<serializers.webhooks.getAListOfWebhooks.Response.Raw, Api.Webhook[]>;
export declare namespace Response {
    type Raw = Webhook.Raw[];
}
