/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Api from "../../../../api/index";
import * as core from "../../../../core";
export declare const AlertsDeleteResponse: core.serialization.ObjectSchema<serializers.AlertsDeleteResponse.Raw, Api.AlertsDeleteResponse>;
export declare namespace AlertsDeleteResponse {
    interface Raw {
        alert_id?: string | null;
        deleted?: boolean | null;
    }
}
