"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiTimeoutError = void 0;
class ApiTimeoutError extends Error {
    constructor(message) {
        super(message);
        Object.setPrototypeOf(this, ApiTimeoutError.prototype);
    }
}
exports.ApiTimeoutError = ApiTimeoutError;
