/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Api from "../../../../api/index";
import * as core from "../../../../core";
import { Website } from "../../../types/Website";
export declare const Response: core.serialization.Schema<serializers.websites.getAListOfWebsites.Response.Raw, Api.Website[]>;
export declare namespace Response {
    type Raw = Website.Raw[];
}
