/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as Api from "../../../../api/index";
import * as core from "../../../../core";
export declare const DeleteAlertsIdResponse: core.serialization.ObjectSchema<serializers.DeleteAlertsIdResponse.Raw, Api.DeleteAlertsIdResponse>;
export declare namespace DeleteAlertsIdResponse {
    interface Raw {
        alert_id?: string | null;
        deleted?: boolean | null;
    }
}
