/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         host: "host"
 *     }
 */
export interface WebsiteCreate {
    /** Host */
    host: string;
    /** Description */
    description?: string;
}
