/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const AlertEvent: core.serialization.ObjectSchema<serializers.AlertEvent.Raw, Api.AlertEvent>;
export declare namespace AlertEvent {
    interface Raw {
        kind?: number | null;
        value?: string | null;
    }
}
