/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const AlertProviderEnum: core.serialization.Schema<serializers.AlertProviderEnum.Raw, Api.AlertProviderEnum>;
export declare namespace AlertProviderEnum {
    type Raw = "slack" | "webhooks";
}
