/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
import { ErrorResponseError } from "./ErrorResponseError";
export declare const ErrorResponse: core.serialization.ObjectSchema<serializers.ErrorResponse.Raw, Api.ErrorResponse>;
export declare namespace ErrorResponse {
    interface Raw {
        error?: ErrorResponseError.Raw | null;
    }
}
