/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const Pagination: core.serialization.ObjectSchema<serializers.Pagination.Raw, Api.Pagination>;
export declare namespace Pagination {
    interface Raw {
        num?: number | null;
        size?: number | null;
    }
}
