/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const RelativeDateString: core.serialization.Schema<serializers.RelativeDateString.Raw, Api.RelativeDateString>;
export declare namespace RelativeDateString {
    type Raw = "TODAY" | "YESTERDAY" | "BEGINNING_OF_WEEK" | "BEGINNING_OF_MONTH" | "BEGINNING_OF_PREV_MONTH" | "TODAY-7DAYS" | "TODAY-30DAYS";
}
