/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const SessionVisitorDataParams: core.serialization.ObjectSchema<serializers.SessionVisitorDataParams.Raw, Api.SessionVisitorDataParams>;
export declare namespace SessionVisitorDataParams {
    interface Raw {
        name?: string | null;
        value?: string | null;
    }
}
