/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const SessionUtmData: core.serialization.ObjectSchema<serializers.SessionUtmData.Raw, Api.SessionUtmData>;
export declare namespace SessionUtmData {
    interface Raw {
        source?: string | null;
        medium?: string | null;
        campaign?: string | null;
        term?: string | null;
        content?: string | null;
    }
}
