/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const SessionEventsStatisticsData: core.serialization.ObjectSchema<serializers.SessionEventsStatisticsData.Raw, Api.SessionEventsStatisticsData>;
export declare namespace SessionEventsStatisticsData {
    interface Raw {
        clicks?: number | null;
        error_clicks?: number | null;
        rage_clicks?: number | null;
        error_logs?: number | null;
        net_errors?: number | null;
    }
}
