/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const SessionPageViewViewPortData: core.serialization.ObjectSchema<serializers.SessionPageViewViewPortData.Raw, Api.SessionPageViewViewPortData>;
export declare namespace SessionPageViewViewPortData {
    interface Raw {
        height?: number | null;
        width?: number | null;
    }
}
