/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
import { SessionVisitorDataGeolocation } from "./SessionVisitorDataGeolocation";
import { SessionVisitorDataParams } from "./SessionVisitorDataParams";
export declare const SessionVisitorData: core.serialization.ObjectSchema<serializers.SessionVisitorData.Raw, Api.SessionVisitorData>;
export declare namespace SessionVisitorData {
    interface Raw {
        id?: string | null;
        ip?: string | null;
        geolocation?: SessionVisitorDataGeolocation.Raw | null;
        name?: string | null;
        email?: string | null;
        email_hash?: string | null;
        params?: SessionVisitorDataParams.Raw[] | null;
        last_session_timestamp?: number | null;
        first_session_timestamp?: number | null;
    }
}
