/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const SessionPageViewsStatisticsData: core.serialization.ObjectSchema<serializers.SessionPageViewsStatisticsData.Raw, Api.SessionPageViewsStatisticsData>;
export declare namespace SessionPageViewsStatisticsData {
    interface Raw {
        count?: number | null;
    }
}
