"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.Session = void 0;
const core = __importStar(require("../../core"));
const SessionVisitorData_1 = require("./SessionVisitorData");
const SessionResolutionData_1 = require("./SessionResolutionData");
const SessionOsData_1 = require("./SessionOsData");
const SessionBrowserData_1 = require("./SessionBrowserData");
const SessionUtmData_1 = require("./SessionUtmData");
const SessionPageViewsStatisticsData_1 = require("./SessionPageViewsStatisticsData");
const SessionEventsStatisticsData_1 = require("./SessionEventsStatisticsData");
exports.Session = core.serialization.object({
    id: core.serialization.string().optional(),
    websiteId: core.serialization.property("website_id", core.serialization.string().optional()),
    sessionUrl: core.serialization.property("session_url", core.serialization.string().optional()),
    creationTimestamp: core.serialization.property("creation_timestamp", core.serialization.number().optional()),
    duration: core.serialization.number().optional(),
    endTimestamp: core.serialization.property("end_timestamp", core.serialization.number().optional()),
    activeTime: core.serialization.property("active_time", core.serialization.number().optional()),
    endUrl: core.serialization.property("end_url", core.serialization.string().optional()),
    expirationTimestamp: core.serialization.property("expiration_timestamp", core.serialization.number().optional()),
    lastEventTimestamp: core.serialization.property("last_event_timestamp", core.serialization.number().optional()),
    product: core.serialization.string().optional(),
    device: core.serialization.string().optional(),
    tags: core.serialization.list(core.serialization.string()).optional(),
    lastSeenPageViewId: core.serialization.property("last_seen_page_view_id", core.serialization.string().optional()),
    seen: core.serialization.boolean().optional(),
    referrer: core.serialization.string().optional(),
    startUrl: core.serialization.property("start_url", core.serialization.string().optional()),
    visitorFirstSession: core.serialization.property("visitor_first_session", core.serialization.boolean().optional()),
    engagmentScore: core.serialization.property("engagment_score", core.serialization.number().optional()),
    visitor: SessionVisitorData_1.SessionVisitorData.optional(),
    resolution: SessionResolutionData_1.SessionResolutionData.optional(),
    os: SessionOsData_1.SessionOsData.optional(),
    browser: SessionBrowserData_1.SessionBrowserData.optional(),
    utm: SessionUtmData_1.SessionUtmData.optional(),
    pageViewsStatistics: core.serialization.property("page_views_statistics", SessionPageViewsStatisticsData_1.SessionPageViewsStatisticsData.optional()),
    eventsStatistics: core.serialization.property("events_statistics", SessionEventsStatisticsData_1.SessionEventsStatisticsData.optional()),
});
