/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../index";
import * as Api from "../../api/index";
import * as core from "../../core";
export declare const WebhookDeleted: core.serialization.ObjectSchema<serializers.WebhookDeleted.Raw, Api.WebhookDeleted>;
export declare namespace WebhookDeleted {
    interface Raw {
        webhook_id?: string | null;
        deleted?: boolean | null;
    }
}
