/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Api from "../../../index";
export declare namespace Alerts {
    interface Options {
        environment?: core.Supplier<environments.ApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class Alerts {
    protected readonly _options: Alerts.Options;
    constructor(_options: Alerts.Options);
    /**
     * @param {Alerts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.BadRequestError}
     * @throws {@link Api.InternalServerError}
     *
     * @example
     *     await client.alerts.getAllAlerts()
     */
    getAllAlerts(requestOptions?: Alerts.RequestOptions): Promise<Api.Alert[]>;
    /**
     * @param {Api.AlertCreate} request
     * @param {Alerts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.BadRequestError}
     * @throws {@link Api.InternalServerError}
     *
     * @example
     *     await client.alerts.createAnAlert({
     *         name: "name",
     *         events: [{}],
     *         provider: "slack"
     *     })
     */
    createAnAlert(request: Api.AlertCreate, requestOptions?: Alerts.RequestOptions): Promise<Api.Alert>;
    /**
     * @param {string} id
     * @param {Api.AlertUpdate} request
     * @param {Alerts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.BadRequestError}
     * @throws {@link Api.InternalServerError}
     *
     * @example
     *     await client.alerts.updateAnAlertById("id")
     */
    updateAnAlertById(id: string, request?: Api.AlertUpdate, requestOptions?: Alerts.RequestOptions): Promise<Api.Alert>;
    /**
     * @param {string} id
     * @param {Alerts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Api.BadRequestError}
     * @throws {@link Api.InternalServerError}
     *
     * @example
     *     await client.alerts.deleteAnAlertById("id")
     */
    deleteAnAlertById(id: string, requestOptions?: Alerts.RequestOptions): Promise<Api.DeleteAlertsIdResponse>;
    protected _getCustomAuthorizationHeaders(): Promise<{
        Authorization: string;
    }>;
}
